-
  name: C
  compiler: /usr/bin/gcc -x c -lm %{source} -o %{output}
  description: GCC version 4.4.3
-
  name: Pascal
  extension: pas
  compiler: /usr/bin/fpc %{source} -o%{source}
  description: Free Pascal Compiler version 2.4
-
  name: C++
  compiler: /usr/bin/g++ -O3 -x c++ %{source} -o %{output}
  description: g++ gcc version 4.4.3
-
  name: Java
  compiler: /usr/bin/gcj %{source} -o %{output} --main=%{basename} -lm
  memory: 14000
  description: gcj gcc version 4.4.3
-
  name: Ruby
  extension: '.rb'
  interpreter: /opt/ruby/bin/ruby
  memory: 60000
  time: 2
  description: ruby 2.0.0dev
  processes: 3
-
  name: Python
  extension: '.py'
  interpreter: /opt/python/bin/python3
  memory: 60000
  time: 2
  description: Python 3.2
-
  name: Go
  compiler: /opt/go/bin build -o %{output} %{source}
  description: go version go1.4.2
-
  name: 'Mono'
  compiler: gmcs -out:Program.exe -target:exe %{source} && mkbundle Program.exe --deps --static -o Program.c -oo Program.o -c && cc -ggdb -o %{output} -Wall Program.c -I/usr/include/mono-2.0 -L/usr/lib -lmono-2.0 -lm Program.o
  extension: '.cs'
  memory: 14000
  description: "Mono compiler"
