name: "Prudge"
slogan: "Happy Coding"
copyright: "All rights reserved"
description: "Programming contest organization, problem solving site"
notifier:
  from: "email@example.com"
  host: "example.com"
