development: &my_settings
  mem_limit: 256M
  port: 3317
  listen: 127.0.0.1:3317
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  html_strip: 1
  charset_type: utf-8
  charset_table: a..z, A..Z->a..z, 0..9, U+0430..U+044f, U+0410..U+042f->U+0430..U+044f, U+0451, U+0401->U+0451, U+04e9, U+04e8->U+04e9, U+04af, U+04ae->U+04af

test:
  <<: *my_settings

production:
  <<: *my_settings
  pid_file: /APPROOT/shared/pids/sphinx.pid
  config_file: /APPROOT/shared/config/sphinx.conf
  searchd_file_path: /APPROOT/shared/sphinx
  searchd_binary_name: /usr/local/sbin/searchd
  indexer_binary_name: /usr/local/bin/indexer
